#!/usr/bin/env python
from tryton_mirror import CommandHandler

if __name__ == '__main__':
    handler = CommandHandler()
    handler.do_setup()
    handler.do_clone_all()
    handler.do_pull_all()
    handler.do_hg_to_git()
    handler.do_push_to_remotes()
